// Generated by Haxe 3.4.7
(function ($hx_exports, $global) { "use strict";
$hx_exports["me"] = $hx_exports["me"] || {};
$hx_exports["me"]["cunity"] = $hx_exports["me"]["cunity"] || {};
$hx_exports["me"]["cunity"]["debug"] = $hx_exports["me"]["cunity"]["debug"] || {};
$hx_exports["me"]["cunity"]["debug"]["Out"] = $hx_exports["me"]["cunity"]["debug"]["Out"] || {};
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var React_Component = require("react").Component;
var App = function() {
	App.store = ApplicationStore.create();
	this.state = App.store.getState().appWare;
	haxe_Log.trace(Reflect.fields(this.state),{ fileName : "App.hx", lineNumber : 47, className : "App", methodName : "new"});
	React_Component.call(this,this.props,this.state);
};
App.__name__ = ["App"];
App.edump = function(el) {
	me_cunity_debug_Out.dumpObject(el,{ fileName : "App.hx", lineNumber : 72, className : "App", methodName : "edump"});
	return "OK";
};
App.renderContent = function(state) {
	if(state.component == null) {
		return { "$$typeof" : $$tre, type : "span", props : { children : "Loading..."}, key : null, ref : null};
	} else {
		return { "$$typeof" : $$tre, type : state.component, props : { }, key : null, ref : null};
	}
};
App.__super__ = React_Component;
App.prototype = $extend(React_Component.prototype,{
	backListener: null
	,browserHistory: null
	,componentDidMount: function() {
		var _g = this.state.route;
		haxe_Log.trace(this.state.route,{ fileName : "App.hx", lineNumber : 61, className : "App", methodName : "componentDidMount"});
	}
	,componentDidCatch: function(error,info) {
		this.setState({ hasError : true});
		haxe_Log.trace(error,{ fileName : "App.hx", lineNumber : 69, className : "App", methodName : "componentDidCatch"});
	}
	,render: function() {
		return { "$$typeof" : $$tre, type : redux_react_Provider, props : { store : App.store, children : { "$$typeof" : $$tre, type : view_UiView, props : { }, key : null, ref : null}}, key : null, ref : null};
	}
	,__class__: App
});
var ApplicationStore = function() { };
ApplicationStore.__name__ = ["ApplicationStore"];
ApplicationStore.create = function() {
	var appWare = new model_AppWare();
	var rootReducer = redux_Redux.combineReducers({ appWare : redux_StoreBuilder.mapReducer(action_AppAction,appWare)});
	var middleware = redux_Redux.applyMiddleware(redux_StoreBuilder.mapMiddleware(action_AppAction,appWare));
	return redux_StoreBuilder.createStore(rootReducer,null,middleware);
};
ApplicationStore.startup = function(store) {
	haxe_Log.trace(store,{ fileName : "ApplicationStore.hx", lineNumber : 37, className : "ApplicationStore", methodName : "startup"});
};
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = ["EReg"];
EReg.prototype = {
	r: null
	,match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw new js__$Boot_HaxeError("EReg::matched");
		}
	}
	,__class__: EReg
};
var Go = function() { };
Go.__name__ = ["Go"];
Go.main = function() {
	Go.render(Go.createRoot());
};
Go.createRoot = function() {
	var root = window.document.createElement("div");
	root.className = "rootBox";
	window.document.body.appendChild(root);
	return root;
};
Go.render = function(root) {
	var app = ReactDOM.render({ "$$typeof" : $$tre, type : App, props : { }, key : null, ref : null},root);
};
var HxOverrides = function() { };
HxOverrides.__name__ = ["HxOverrides"];
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.remove = function(a,obj) {
	var i = a.indexOf(obj);
	if(i == -1) {
		return false;
	}
	a.splice(i,1);
	return true;
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.__name__ = ["Lambda"];
Lambda.has = function(it,elt) {
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(x1 == elt) {
			return true;
		}
	}
	return false;
};
Lambda.exists = function(it,f) {
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(f(x1)) {
			return true;
		}
	}
	return false;
};
Lambda.filter = function(it,f) {
	var l = new List();
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(f(x1)) {
			l.add(x1);
		}
	}
	return l;
};
var List = function() {
	this.length = 0;
};
List.__name__ = ["List"];
List.prototype = {
	h: null
	,q: null
	,length: null
	,add: function(item) {
		var x = new _$List_ListNode(item,null);
		if(this.h == null) {
			this.h = x;
		} else {
			this.q.next = x;
		}
		this.q = x;
		this.length++;
	}
	,push: function(item) {
		var x = new _$List_ListNode(item,this.h);
		this.h = x;
		if(this.q == null) {
			this.q = x;
		}
		this.length++;
	}
	,iterator: function() {
		return new _$List_ListIterator(this.h);
	}
	,__class__: List
};
var _$List_ListNode = function(item,next) {
	this.item = item;
	this.next = next;
};
_$List_ListNode.__name__ = ["_List","ListNode"];
_$List_ListNode.prototype = {
	item: null
	,next: null
	,__class__: _$List_ListNode
};
var _$List_ListIterator = function(head) {
	this.head = head;
};
_$List_ListIterator.__name__ = ["_List","ListIterator"];
_$List_ListIterator.prototype = {
	head: null
	,hasNext: function() {
		return this.head != null;
	}
	,next: function() {
		var val = this.head.item;
		this.head = this.head.next;
		return val;
	}
	,__class__: _$List_ListIterator
};
Math.__name__ = ["Math"];
var Reflect = function() { };
Reflect.__name__ = ["Reflect"];
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) {
			a.push(f);
		}
		}
	}
	return a;
};
Reflect.isFunction = function(f) {
	if(typeof(f) == "function") {
		return !(f.__name__ || f.__ename__);
	} else {
		return false;
	}
};
var Std = function() { };
Std.__name__ = ["Std"];
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) {
		v = parseInt(x);
	}
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringBuf = function() {
	this.b = "";
};
StringBuf.__name__ = ["StringBuf"];
StringBuf.prototype = {
	b: null
	,__class__: StringBuf
};
var StringTools = function() { };
StringTools.__name__ = ["StringTools"];
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
var ValueType = { __ename__ : ["ValueType"], __constructs__ : ["TNull","TInt","TFloat","TBool","TObject","TFunction","TClass","TEnum","TUnknown"] };
ValueType.TNull = ["TNull",0];
ValueType.TNull.__enum__ = ValueType;
ValueType.TInt = ["TInt",1];
ValueType.TInt.__enum__ = ValueType;
ValueType.TFloat = ["TFloat",2];
ValueType.TFloat.__enum__ = ValueType;
ValueType.TBool = ["TBool",3];
ValueType.TBool.__enum__ = ValueType;
ValueType.TObject = ["TObject",4];
ValueType.TObject.__enum__ = ValueType;
ValueType.TFunction = ["TFunction",5];
ValueType.TFunction.__enum__ = ValueType;
ValueType.TClass = function(c) { var $x = ["TClass",6,c]; $x.__enum__ = ValueType; return $x; };
ValueType.TEnum = function(e) { var $x = ["TEnum",7,e]; $x.__enum__ = ValueType; return $x; };
ValueType.TUnknown = ["TUnknown",8];
ValueType.TUnknown.__enum__ = ValueType;
var Type = function() { };
Type.__name__ = ["Type"];
Type.getEnum = function(o) {
	if(o == null) {
		return null;
	}
	return o.__enum__;
};
Type.getClassName = function(c) {
	var a = c.__name__;
	if(a == null) {
		return null;
	}
	return a.join(".");
};
Type.getEnumName = function(e) {
	var a = e.__ename__;
	return a.join(".");
};
Type.getInstanceFields = function(c) {
	var a = [];
	for(var i in c.prototype) a.push(i);
	HxOverrides.remove(a,"__class__");
	HxOverrides.remove(a,"__properties__");
	return a;
};
Type["typeof"] = function(v) {
	var _g = typeof(v);
	switch(_g) {
	case "boolean":
		return ValueType.TBool;
	case "function":
		if(v.__name__ || v.__ename__) {
			return ValueType.TObject;
		}
		return ValueType.TFunction;
	case "number":
		if(Math.ceil(v) == v % 2147483648.0) {
			return ValueType.TInt;
		}
		return ValueType.TFloat;
	case "object":
		if(v == null) {
			return ValueType.TNull;
		}
		var e = v.__enum__;
		if(e != null) {
			return ValueType.TEnum(e);
		}
		var c = js_Boot.getClass(v);
		if(c != null) {
			return ValueType.TClass(c);
		}
		return ValueType.TObject;
	case "string":
		return ValueType.TClass(String);
	case "undefined":
		return ValueType.TNull;
	default:
		return ValueType.TUnknown;
	}
};
var Webpack = function() { };
Webpack.__name__ = ["Webpack"];
var action_AppAction = { __ename__ : ["action","AppAction"], __constructs__ : ["Load","SetLocale","SetTheme"] };
action_AppAction.Load = ["Load",0];
action_AppAction.Load.__enum__ = action_AppAction;
action_AppAction.SetLocale = function(locale) { var $x = ["SetLocale",1,locale]; $x.__enum__ = action_AppAction; return $x; };
action_AppAction.SetTheme = function(color) { var $x = ["SetTheme",2,color]; $x.__enum__ = action_AppAction; return $x; };
var action_HistoryAction = { __ename__ : ["action","HistoryAction"], __constructs__ : ["Pop","Push","Replace","Go","Back","Forward"] };
action_HistoryAction.Pop = ["Pop",0];
action_HistoryAction.Pop.__enum__ = action_HistoryAction;
action_HistoryAction.Push = ["Push",1];
action_HistoryAction.Push.__enum__ = action_HistoryAction;
action_HistoryAction.Replace = ["Replace",2];
action_HistoryAction.Replace.__enum__ = action_HistoryAction;
action_HistoryAction.Go = ["Go",3];
action_HistoryAction.Go.__enum__ = action_HistoryAction;
action_HistoryAction.Back = ["Back",4];
action_HistoryAction.Back.__enum__ = action_HistoryAction;
action_HistoryAction.Forward = ["Forward",5];
action_HistoryAction.Forward.__enum__ = action_HistoryAction;
var bulma_$components_Button = require("reactbulma").Button;
var Icon = require("reactbulma").Icon;
var bulma_$components_Tabs = require("reactbulma").Tabs;
var haxe_StackItem = { __ename__ : ["haxe","StackItem"], __constructs__ : ["CFunction","Module","FilePos","Method","LocalFunction"] };
haxe_StackItem.CFunction = ["CFunction",0];
haxe_StackItem.CFunction.__enum__ = haxe_StackItem;
haxe_StackItem.Module = function(m) { var $x = ["Module",1,m]; $x.__enum__ = haxe_StackItem; return $x; };
haxe_StackItem.FilePos = function(s,file,line) { var $x = ["FilePos",2,s,file,line]; $x.__enum__ = haxe_StackItem; return $x; };
haxe_StackItem.Method = function(classname,method) { var $x = ["Method",3,classname,method]; $x.__enum__ = haxe_StackItem; return $x; };
haxe_StackItem.LocalFunction = function(v) { var $x = ["LocalFunction",4,v]; $x.__enum__ = haxe_StackItem; return $x; };
var haxe_CallStack = function() { };
haxe_CallStack.__name__ = ["haxe","CallStack"];
haxe_CallStack.getStack = function(e) {
	if(e == null) {
		return [];
	}
	var oldValue = Error.prepareStackTrace;
	Error.prepareStackTrace = function(error,callsites) {
		var stack = [];
		var _g = 0;
		while(_g < callsites.length) {
			var site = callsites[_g];
			++_g;
			if(haxe_CallStack.wrapCallSite != null) {
				site = haxe_CallStack.wrapCallSite(site);
			}
			var method = null;
			var fullName = site.getFunctionName();
			if(fullName != null) {
				var idx = fullName.lastIndexOf(".");
				if(idx >= 0) {
					var className = HxOverrides.substr(fullName,0,idx);
					var methodName = HxOverrides.substr(fullName,idx + 1,null);
					method = haxe_StackItem.Method(className,methodName);
				}
			}
			stack.push(haxe_StackItem.FilePos(method,site.getFileName(),site.getLineNumber()));
		}
		return stack;
	};
	var a = haxe_CallStack.makeStack(e.stack);
	Error.prepareStackTrace = oldValue;
	return a;
};
haxe_CallStack.callStack = function() {
	try {
		throw new Error();
	} catch( e ) {
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		var a = haxe_CallStack.getStack(e);
		a.shift();
		return a;
	}
};
haxe_CallStack.makeStack = function(s) {
	if(s == null) {
		return [];
	} else if(typeof(s) == "string") {
		var stack = s.split("\n");
		if(stack[0] == "Error") {
			stack.shift();
		}
		var m = [];
		var rie10 = new EReg("^   at ([A-Za-z0-9_. ]+) \\(([^)]+):([0-9]+):([0-9]+)\\)$","");
		var _g = 0;
		while(_g < stack.length) {
			var line = stack[_g];
			++_g;
			if(rie10.match(line)) {
				var path = rie10.matched(1).split(".");
				var meth = path.pop();
				var file = rie10.matched(2);
				var line1 = Std.parseInt(rie10.matched(3));
				m.push(haxe_StackItem.FilePos(meth == "Anonymous function" ? haxe_StackItem.LocalFunction() : meth == "Global code" ? null : haxe_StackItem.Method(path.join("."),meth),file,line1));
			} else {
				m.push(haxe_StackItem.Module(StringTools.trim(line)));
			}
		}
		return m;
	} else {
		return s;
	}
};
var haxe_Http = function(url) {
	this.url = url;
	this.headers = new List();
	this.params = new List();
	this.async = true;
	this.withCredentials = false;
};
haxe_Http.__name__ = ["haxe","Http"];
haxe_Http.prototype = {
	url: null
	,responseData: null
	,async: null
	,withCredentials: null
	,postData: null
	,headers: null
	,params: null
	,setParameter: function(param,value) {
		this.params = Lambda.filter(this.params,function(p) {
			return p.param != param;
		});
		this.params.push({ param : param, value : value});
		return this;
	}
	,req: null
	,request: function(post) {
		var me = this;
		me.responseData = null;
		var r = this.req = js_Browser.createXMLHttpRequest();
		var onreadystatechange = function(_) {
			if(r.readyState != 4) {
				return;
			}
			var s;
			try {
				s = r.status;
			} catch( e ) {
				s = null;
			}
			if(s != null && "undefined" !== typeof window) {
				var protocol = window.location.protocol.toLowerCase();
				var rlocalProtocol = new EReg("^(?:about|app|app-storage|.+-extension|file|res|widget):$","");
				var isLocal = rlocalProtocol.match(protocol);
				if(isLocal) {
					if(r.responseText != null) {
						s = 200;
					} else {
						s = 404;
					}
				}
			}
			if(s == undefined) {
				s = null;
			}
			if(s != null) {
				me.onStatus(s);
			}
			if(s != null && s >= 200 && s < 400) {
				me.req = null;
				me.onData(me.responseData = r.responseText);
			} else if(s == null) {
				me.req = null;
				me.onError("Failed to connect or resolve host");
			} else {
				switch(s) {
				case 12007:
					me.req = null;
					me.onError("Unknown host");
					break;
				case 12029:
					me.req = null;
					me.onError("Failed to connect to host");
					break;
				default:
					me.req = null;
					me.responseData = r.responseText;
					me.onError("Http Error #" + r.status);
				}
			}
		};
		if(this.async) {
			r.onreadystatechange = onreadystatechange;
		}
		var uri = this.postData;
		if(uri != null) {
			post = true;
		} else {
			var _g_head = this.params.h;
			while(_g_head != null) {
				var val = _g_head.item;
				_g_head = _g_head.next;
				var p = val;
				if(uri == null) {
					uri = "";
				} else {
					uri += "&";
				}
				var s1 = p.param;
				var uri1 = encodeURIComponent(s1) + "=";
				var s2 = p.value;
				uri += uri1 + encodeURIComponent(s2);
			}
		}
		try {
			if(post) {
				r.open("POST",this.url,this.async);
			} else if(uri != null) {
				var question = this.url.split("?").length <= 1;
				r.open("GET",this.url + (question ? "?" : "&") + uri,this.async);
				uri = null;
			} else {
				r.open("GET",this.url,this.async);
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			me.req = null;
			this.onError(e1.toString());
			return;
		}
		r.withCredentials = this.withCredentials;
		if(!Lambda.exists(this.headers,function(h) {
			return h.header == "Content-Type";
		}) && post && this.postData == null) {
			r.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
		}
		var _g_head1 = this.headers.h;
		while(_g_head1 != null) {
			var val1 = _g_head1.item;
			_g_head1 = _g_head1.next;
			var h1 = val1;
			r.setRequestHeader(h1.header,h1.value);
		}
		r.send(uri);
		if(!this.async) {
			onreadystatechange(null);
		}
	}
	,onData: function(data) {
	}
	,onError: function(msg) {
	}
	,onStatus: function(status) {
	}
	,__class__: haxe_Http
};
var haxe_Log = function() { };
haxe_Log.__name__ = ["haxe","Log"];
haxe_Log.trace = function(v,infos) {
	js_Boot.__trace(v,infos);
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = ["js","_Boot","HaxeError"];
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	val: null
	,__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = ["js","Boot"];
js_Boot.__unhtml = function(s) {
	return s.split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;");
};
js_Boot.__trace = function(v,i) {
	var msg = i != null ? i.fileName + ":" + i.lineNumber + ": " : "";
	msg += js_Boot.__string_rec(v,"");
	if(i != null && i.customParams != null) {
		var _g = 0;
		var _g1 = i.customParams;
		while(_g < _g1.length) {
			var v1 = _g1[_g];
			++_g;
			msg += "," + js_Boot.__string_rec(v1,"");
		}
	}
	var d;
	var tmp;
	if(typeof(document) != "undefined") {
		d = document.getElementById("haxe:trace");
		tmp = d != null;
	} else {
		tmp = false;
	}
	if(tmp) {
		d.innerHTML += js_Boot.__unhtml(msg) + "<br/>";
	} else if(typeof console != "undefined" && console.log != null) {
		console.log(msg);
	}
};
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var js_Browser = function() { };
js_Browser.__name__ = ["js","Browser"];
js_Browser.createXMLHttpRequest = function() {
	if(typeof XMLHttpRequest != "undefined") {
		return new XMLHttpRequest();
	}
	if(typeof ActiveXObject != "undefined") {
		return new ActiveXObject("Microsoft.XMLHTTP");
	}
	throw new js__$Boot_HaxeError("Unable to create XMLHttpRequest object.");
};
var js_jq_JHelper = function() { };
js_jq_JHelper.__name__ = ["js","jq","JHelper"];
js_jq_JHelper.J = function(html) {
	return $(html);
};
js_jq_JHelper.vsprintf = function(format,args) {
	return vsprintf(format,args);
};
var me_cunity_debug_DebugOutput = { __ename__ : ["me","cunity","debug","DebugOutput"], __constructs__ : ["CONSOLE","HAXE","NATIVE","LOG"] };
me_cunity_debug_DebugOutput.CONSOLE = ["CONSOLE",0];
me_cunity_debug_DebugOutput.CONSOLE.__enum__ = me_cunity_debug_DebugOutput;
me_cunity_debug_DebugOutput.HAXE = ["HAXE",1];
me_cunity_debug_DebugOutput.HAXE.__enum__ = me_cunity_debug_DebugOutput;
me_cunity_debug_DebugOutput.NATIVE = ["NATIVE",2];
me_cunity_debug_DebugOutput.NATIVE.__enum__ = me_cunity_debug_DebugOutput;
me_cunity_debug_DebugOutput.LOG = ["LOG",3];
me_cunity_debug_DebugOutput.LOG.__enum__ = me_cunity_debug_DebugOutput;
var me_cunity_debug_Out = $hx_exports["Out"] = function() { };
me_cunity_debug_Out.__name__ = ["me","cunity","debug","Out"];
me_cunity_debug_Out._trace = function(v,i) {
	if(me_cunity_debug_Out.suspended) {
		return;
	}
	var warned = false;
	if(i != null && Object.prototype.hasOwnProperty.call(i,"customParams")) {
		i = i.customParams[0];
	}
	var msg = i != null ? i.fileName + ":" + i.methodName + ":" + i.lineNumber + ":" : "";
	msg += Std.string(v);
	var _g = me_cunity_debug_Out.traceTarget;
	switch(_g[1]) {
	case 0:
		debug(msg);
		break;
	case 1:
		var msg1 = i != null ? i.fileName + ":" + i.lineNumber + ":" + i.methodName + ":" : "";
		msg1 += Std.string(v) + "<br/>";
		var d = window.document.getElementById("haxe:trace");
		if(d == null && !warned) {
			warned = true;
			alert("No haxe:trace element defined\n" + msg1);
		} else {
			d.innerHTML += msg1;
		}
		break;
	case 2:
		console.log(msg);
		break;
	case 3:
		$.post(window.location.protocol + "//" + window.location.host + "/inc/functions.php",{ log : 1, m : msg});
		break;
	}
};
me_cunity_debug_Out.log2 = function(v,i) {
	var msg = i != null ? i.fileName + ":" + i.lineNumber + ":" + i.methodName + ":" : "";
	msg += Std.string(v);
	var http = new haxe_Http("http://localhost/devel/php/jsLog.php");
	http.setParameter("log",msg);
	http.async = true;
	http.onData = function(data) {
		if(data != "OK") {
			haxe_Log.trace(data,{ fileName : "Out.hx", lineNumber : 203, className : "me.cunity.debug.Out", methodName : "log2"});
		}
	};
	http.request(true);
};
me_cunity_debug_Out.dumpLayout = function(dI,recursive,i) {
	if(recursive == null) {
		recursive = false;
	}
	me_cunity_debug_Out.dumpJLayout($(dI),recursive,i);
};
me_cunity_debug_Out.dumpJLayout = function(jQ,recursive,i) {
	if(recursive == null) {
		recursive = false;
	}
	if(jQ.length == 0) {
		return;
	}
	var m = jQ.attr("id") + " left:" + jQ.position().left + " top:" + jQ.position().top + " width:" + jQ.width() + " height:" + jQ.height() + " visibility:" + jQ.css("visibility") + " display:" + jQ.css("display") + " position:" + jQ.css("position") + " class:" + jQ.attr("class") + " overflow:" + jQ.css("overflow") + " zIndex:" + jQ.css("z-index") + " opacity:" + jQ.css("opacity");
	me_cunity_debug_Out._trace(m,i);
	if(recursive && jQ.parent().attr("id") != "bgBox") {
		me_cunity_debug_Out.dumpJLayout(jQ.parent(),true,i);
	}
};
me_cunity_debug_Out.dumpObjectRSafe = function(root,recursive,i) {
	if(recursive == null) {
		recursive = false;
	}
	var oCopy = { };
	var _g = 0;
	var _g1 = Reflect.fields(root);
	while(_g < _g1.length) {
		var f = _g1[_g];
		++_g;
		if(f == "parentView") {
			oCopy.parentView = root.parentView.instancePath;
			continue;
		}
		oCopy[f] = Reflect.field(root,f);
	}
	me_cunity_debug_Out.dumpObject(oCopy,i);
};
me_cunity_debug_Out.dumpObjectTree = $hx_exports["me"]["cunity"]["debug"]["Out"]["dumpObjectTree"] = function(root,recursive,i) {
	if(recursive == null) {
		recursive = false;
	}
	me_cunity_debug_Out.dumpedObjects = [];
	me_cunity_debug_Out._dumpObjectTree(root,Type["typeof"](root),recursive,i);
};
me_cunity_debug_Out._dumpObjectTree = function(root,parent,recursive,i) {
	var m;
	var o = root;
	if((o == null ? null : js_Boot.getClass(o)) != null) {
		var o1 = root;
		m = Type.getClassName(o1 == null ? null : js_Boot.getClass(o1));
	} else {
		m = Type["typeof"](root)[0];
	}
	var fields;
	var o2 = root;
	if((o2 == null ? null : js_Boot.getClass(o2)) != null) {
		var o3 = root;
		fields = Type.getInstanceFields(o3 == null ? null : js_Boot.getClass(o3));
	} else {
		fields = Reflect.fields(root);
	}
	if(m == "String") {
		me_cunity_debug_Out._trace(Std.string(root) + " len:" + Std.string(root.length),i);
	} else {
		me_cunity_debug_Out.dumpedObjects.push(root);
		me_cunity_debug_Out._trace(m + " fields:" + fields.length + ":" + fields.slice(0,5).toString(),i);
	}
	try {
		var _g = 0;
		while(_g < fields.length) {
			var f = fields[_g];
			++_g;
			haxe_Log.trace(f,{ fileName : "Out.hx", lineNumber : 307, className : "me.cunity.debug.Out", methodName : "_dumpObjectTree", customParams : [i]});
			if(recursive) {
				if(me_cunity_debug_Out.dumpedObjects.length > 1000) {
					me_cunity_debug_Out._trace(me_cunity_debug_Out.dumpedObjects.toString(),i);
					throw new js__$Boot_HaxeError("oops");
				} else {
					var _o = root[f];
					if(!Lambda.has(me_cunity_debug_Out.dumpedObjects,_o)) {
						me_cunity_debug_Out._dumpObjectTree(_o,Type["typeof"](_o),true,i);
					}
				}
			}
		}
	} catch( ex ) {
		if (ex instanceof js__$Boot_HaxeError) ex = ex.val;
		haxe_Log.trace(ex,{ fileName : "Out.hx", lineNumber : 331, className : "me.cunity.debug.Out", methodName : "_dumpObjectTree"});
	}
};
me_cunity_debug_Out.dumpObject = function(ob,i) {
	var o = ob;
	var tClass = o == null ? null : js_Boot.getClass(o);
	var m;
	if(ob != null) {
		var o1 = ob;
		if(o1 == null) {
			m = null;
		} else {
			m = js_Boot.getClass(o1);
		}
	} else {
		m = ob;
	}
	var m1 = "dumpObject:" + Std.string(m) + "\n";
	var names = [];
	var o2 = ob;
	if((o2 == null ? null : js_Boot.getClass(o2)) != null) {
		var o3 = ob;
		names = Type.getInstanceFields(o3 == null ? null : js_Boot.getClass(o3));
	} else {
		names = Reflect.fields(ob);
	}
	var o4 = ob;
	if((o4 == null ? null : js_Boot.getClass(o4)) != null) {
		var o5 = ob;
		m1 = Type.getClassName(o5 == null ? null : js_Boot.getClass(o5)) + ":\n";
	}
	var _g = 0;
	while(_g < names.length) {
		var name = names[_g];
		++_g;
		if(Lambda.has(me_cunity_debug_Out.skipFields,name)) {
			m1 += "" + name + ":skipped\n";
			continue;
		}
		try {
			var t = Std.string(Type["typeof"](Reflect.field(ob,name)));
			var tmp = me_cunity_debug_Out.skipFunctions && t == "TFunction";
			m1 += name + ":" + Std.string(Reflect.field(ob,name)) + ":" + t + "\n";
		} catch( ex ) {
			if (ex instanceof js__$Boot_HaxeError) ex = ex.val;
			m1 += name + ":" + Std.string(ex);
		}
	}
	me_cunity_debug_Out._trace(m1,i);
};
me_cunity_debug_Out.dumpStack = function(sA,i) {
	var b = new StringBuf();
	b.b += Std.string("StackDump:" + "\n");
	var _g = 0;
	while(_g < sA.length) {
		var item = sA[_g];
		++_g;
		me_cunity_debug_Out.itemToString(item,b);
		b.b += "\n";
	}
	haxe_Log.trace(b.b,{ fileName : "Out.hx", lineNumber : 429, className : "me.cunity.debug.Out", methodName : "dumpStack", customParams : [i]});
};
me_cunity_debug_Out.itemToString = function(s,b) {
	switch(s[1]) {
	case 0:
		b.b += "a C function";
		break;
	case 1:
		var m = s[2];
		b.b += "module ";
		b.b += m == null ? "null" : "" + m;
		break;
	case 2:
		var line = s[4];
		var file = s[3];
		var s1 = s[2];
		if(s1 != null) {
			me_cunity_debug_Out.itemToString(s1,b);
			b.b += " (";
		}
		b.b += file == null ? "null" : "" + file;
		b.b += " line ";
		b.b += line == null ? "null" : "" + line;
		if(s1 != null) {
			b.b += ")\n";
		}
		break;
	case 3:
		var meth = s[3];
		var cname = s[2];
		b.b += cname == null ? "null" : "" + cname;
		b.b += ".";
		b.b += meth == null ? "null" : "" + meth;
		b.b += "\n";
		break;
	case 4:
		var v = s[2];
		b.b += Std.string("LocalFunction:" + v);
		break;
	}
};
me_cunity_debug_Out.fTrace = function(str,arr,i) {
	var str_arr = str.split(" @");
	var str_buf_b = "";
	var _g1 = 0;
	var _g = str_arr.length;
	while(_g1 < _g) {
		var i1 = _g1++;
		str_buf_b += Std.string(str_arr[i1]);
		if(arr[i1] != null) {
			str_buf_b += Std.string(arr[i1]);
		}
	}
	me_cunity_debug_Out._trace(str_buf_b,i);
};
var redux_IMiddleware = function() { };
redux_IMiddleware.__name__ = ["redux","IMiddleware"];
redux_IMiddleware.prototype = {
	store: null
	,middleware: null
	,__class__: redux_IMiddleware
};
var redux_IReducer = function() { };
redux_IReducer.__name__ = ["redux","IReducer"];
redux_IReducer.prototype = {
	initState: null
	,reduce: null
	,__class__: redux_IReducer
};
var model_AppWare = function() {
	this.ID = 0;
	this.initState = { route : "", themeColor : "green", locale : "de", history : null, user : new view_User(null,{ id : 1000000666, contact : 1000000666, first_name : "test", last_name : "agent"})};
};
model_AppWare.__name__ = ["model","AppWare"];
model_AppWare.__interfaces__ = [redux_IMiddleware,redux_IReducer];
model_AppWare.prototype = {
	initState: null
	,store: null
	,ID: null
	,loadPending: null
	,reduce: function(state,action) {
		haxe_Log.trace(action,{ fileName : "AppWare.hx", lineNumber : 42, className : "model.AppWare", methodName : "reduce"});
		switch(action[1]) {
		case 0:
			return react_ReactUtil.copy(state,{ loading : true});
		case 1:
			var locale = action[2];
			if(locale != state.locale) {
				return react_ReactUtil.copy(state,{ locale : locale});
			} else {
				return state;
			}
			break;
		case 2:
			var color = action[2];
			if(color != state.themeColor) {
				return react_ReactUtil.copy(state,{ themeColor : color});
			} else {
				return state;
			}
			break;
		}
	}
	,middleware: function(action,next) {
		haxe_Log.trace(action,{ fileName : "AppWare.hx", lineNumber : 72, className : "model.AppWare", methodName : "middleware"});
		return next();
	}
	,__class__: model_AppWare
};
var react_Partial = function() { };
react_Partial.__name__ = ["react","Partial"];
var react_PartialMacro = function() { };
react_PartialMacro.__name__ = ["react","PartialMacro"];
var React = require("react");
var ReactDOM = require("react-dom");
var react_ReactMacro = function() { };
react_ReactMacro.__name__ = ["react","ReactMacro"];
var PropTypes = require("prop-types");
var react_ReactUtil = function() { };
react_ReactUtil.__name__ = ["react","ReactUtil"];
react_ReactUtil.cx = function(arrayOrObject) {
	var array;
	if((arrayOrObject instanceof Array) && arrayOrObject.__enum__ == null) {
		array = arrayOrObject;
	} else {
		array = [arrayOrObject];
	}
	var classes = [];
	var _g = 0;
	while(_g < array.length) {
		var value = array[_g];
		++_g;
		if(value == null) {
			continue;
		}
		if(typeof(value) == "string") {
			classes.push(value);
		} else {
			var _g1 = 0;
			var _g2 = Reflect.fields(value);
			while(_g1 < _g2.length) {
				var field = _g2[_g1];
				++_g1;
				if(Reflect.field(value,field) == true) {
					classes.push(field);
				}
			}
		}
	}
	return classes.join(" ");
};
react_ReactUtil.assign = function(target,sources) {
	var _g = 0;
	while(_g < sources.length) {
		var source = sources[_g];
		++_g;
		if(source != null) {
			var _g1 = 0;
			var _g2 = Reflect.fields(source);
			while(_g1 < _g2.length) {
				var field = _g2[_g1];
				++_g1;
				target[field] = Reflect.field(source,field);
			}
		}
	}
	return target;
};
react_ReactUtil.copy = function(source1,source2) {
	var target = { };
	var _g = 0;
	var _g1 = Reflect.fields(source1);
	while(_g < _g1.length) {
		var field = _g1[_g];
		++_g;
		target[field] = Reflect.field(source1,field);
	}
	if(source2 != null) {
		var _g2 = 0;
		var _g11 = Reflect.fields(source2);
		while(_g2 < _g11.length) {
			var field1 = _g11[_g2];
			++_g2;
			target[field1] = Reflect.field(source2,field1);
		}
	}
	return target;
};
react_ReactUtil.copyWithout = function(source1,source2,fields) {
	var target = { };
	var _g = 0;
	var _g1 = Reflect.fields(source1);
	while(_g < _g1.length) {
		var field = _g1[_g];
		++_g;
		if(!Lambda.has(fields,field)) {
			target[field] = Reflect.field(source1,field);
		}
	}
	if(source2 != null) {
		var _g2 = 0;
		var _g11 = Reflect.fields(source2);
		while(_g2 < _g11.length) {
			var field1 = _g11[_g2];
			++_g2;
			if(!Lambda.has(fields,field1)) {
				target[field1] = Reflect.field(source2,field1);
			}
		}
	}
	return target;
};
react_ReactUtil.mapi = function(items,map) {
	if(items == null) {
		return null;
	}
	var newItems = [];
	var _g1 = 0;
	var _g = items.length;
	while(_g1 < _g) {
		var i = _g1++;
		newItems.push(map(i,items[i]));
	}
	return newItems;
};
react_ReactUtil.cloneChildren = function(children,props) {
	if(Reflect.isFunction(props)) {
		return React.Children.map(children,function(child) {
			return React.cloneElement(child,props(child));
		});
	} else {
		return React.Children.map(children,function(child1) {
			return React.cloneElement(child1,props);
		});
	}
};
react_ReactUtil.shouldComponentUpdate = function(component,nextProps,nextState) {
	if(!(!react_ReactUtil.shallowCompare(component.props,nextProps))) {
		return !react_ReactUtil.shallowCompare(component.state,nextState);
	} else {
		return true;
	}
};
react_ReactUtil.shallowCompare = function(a,b) {
	var aFields = Reflect.fields(a);
	var bFields = Reflect.fields(b);
	if(aFields.length != bFields.length) {
		return false;
	}
	var _g = 0;
	while(_g < aFields.length) {
		var field = aFields[_g];
		++_g;
		if(!Object.prototype.hasOwnProperty.call(b,field) || Reflect.field(b,field) != Reflect.field(a,field)) {
			return false;
		}
	}
	return true;
};
var react_redux_form_ControlText = require("react-redux-form").Control.text;
var react_router_BrowserRouter = require("react-router-dom").BrowserRouter;
var react_router_NavLink = require("react-router-dom").NavLink;
var react_router_Route = require("react-router").Route;
var react_router_Switch = require("react-router").Switch;
var react_router_bundle_Bundle = function() { };
react_router_bundle_Bundle.__name__ = ["react","router","bundle","Bundle"];
var react_router_bundle_BundleLoader1 = function() { };
react_router_bundle_BundleLoader1.__name__ = ["react","router","bundle","BundleLoader1"];
react_router_bundle_BundleLoader1.render = function(props) {
	return React.createElement(react_router_bundle_BundleWrapper,react_ReactUtil.copy(props,{ loader : System.import("!haxe-loader?null/view_DashBoard!").then(function(exports) {
		view_DashBoard = $s.view_DashBoard;
		var _ = view_DashBoard;
		return exports;
	})}));
};
var react_router_bundle_BundleLoader2 = function() { };
react_router_bundle_BundleLoader2.__name__ = ["react","router","bundle","BundleLoader2"];
react_router_bundle_BundleLoader2.render = function(props) {
	return React.createElement(react_router_bundle_BundleWrapper,react_ReactUtil.copy(props,{ loader : System.import("!haxe-loader?null/view_QC!").then(function(exports) {
		view_QC = $s.view_QC;
		var _ = view_QC;
		return exports;
	})}));
};
var react_router_bundle_BundleLoader3 = function() { };
react_router_bundle_BundleLoader3.__name__ = ["react","router","bundle","BundleLoader3"];
react_router_bundle_BundleLoader3.render = function(props) {
	return React.createElement(react_router_bundle_BundleWrapper,react_ReactUtil.copy(props,{ loader : System.import("!haxe-loader?null/view_Contacts!").then(function(exports) {
		view_Contacts = $s.view_Contacts;
		var _ = view_Contacts;
		return exports;
	})}));
};
var react_router_bundle_BundleLoader4 = function() { };
react_router_bundle_BundleLoader4.__name__ = ["react","router","bundle","BundleLoader4"];
react_router_bundle_BundleLoader4.render = function(props) {
	return React.createElement(react_router_bundle_BundleWrapper,react_ReactUtil.copy(props,{ loader : System.import("!haxe-loader?null/view_Accounting!").then(function(exports) {
		view_Accounting = $s.view_Accounting;
		var _ = view_Accounting;
		return exports;
	})}));
};
var react_router_bundle_BundleLoader5 = function() { };
react_router_bundle_BundleLoader5.__name__ = ["react","router","bundle","BundleLoader5"];
react_router_bundle_BundleLoader5.render = function(props) {
	return React.createElement(react_router_bundle_BundleWrapper,react_ReactUtil.copy(props,{ loader : System.import("!haxe-loader?null/view_Reports!").then(function(exports) {
		view_Reports = $s.view_Reports;
		var _ = view_Reports;
		return exports;
	})}));
};
var react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$ = {};
react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$.__name__ = ["react","router","bundle","_BundleWrapper","BundledComponent_Impl_"];
react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$.firstLoad = function(this1) {
	var firstLoad = this1.__alreadyLoaded == null;
	this1.__alreadyLoaded = true;
	return firstLoad;
};
react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$.getOnLoad = function(this1) {
	return this1.onLoad;
};
react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$.toCreateElementType = function(this1) {
	if(this1.__jsxStatic != null) {
		return this1.__jsxStatic;
	}
	return this1;
};
var react_router_bundle_BundleWrapper = function(props) {
	React_Component.call(this,props);
	this.state = { module : null, error : false, errorMessage : null};
};
react_router_bundle_BundleWrapper.__name__ = ["react","router","bundle","BundleWrapper"];
react_router_bundle_BundleWrapper.DefaultLoader = function() {
	return { "$$typeof" : $$tre, type : "div", props : { className : "loader"}, key : null, ref : null};
};
react_router_bundle_BundleWrapper.DefaultError = function() {
	return { "$$typeof" : $$tre, type : "div", props : { className : "error"}, key : null, ref : null};
};
react_router_bundle_BundleWrapper.__super__ = React_Component;
react_router_bundle_BundleWrapper.prototype = $extend(React_Component.prototype,{
	available: null
	,render: function() {
		if(this.state.error) {
			return React.createElement(this.props.error,{ error : this.state.errorMessage});
		}
		var moduleProps = { };
		var _g = 0;
		var _g1 = Reflect.fields(this.props);
		while(_g < _g1.length) {
			var field = _g1[_g];
			++_g;
			switch(field) {
			case "error":case "loader":case "loading":
				break;
			default:
				moduleProps[field] = Reflect.field(this.props,field);
			}
		}
		if(this.state.module != null) {
			return React.createElement(react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$.toCreateElementType(this.state.module),moduleProps);
		} else {
			return React.createElement(this.props.loading,{ });
		}
	}
	,componentWillMount: function() {
		this.available = true;
		this.loadBundle(this.props);
	}
	,componentWillUnmount: function() {
		this.available = false;
	}
	,loadBundle: function(props) {
		var _gthis = this;
		this.setState({ module : null, error : false},function() {
			props.loader.then(function(mod) {
				if(!_gthis.available) {
					return;
				}
				var module = mod;
				while(mod != null) {
					module = mod;
					mod = mod["default"];
				}
				if(react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$.firstLoad(module)) {
					var onLoad = react_router_bundle__$BundleWrapper_BundledComponent_$Impl_$.getOnLoad(module);
					if(onLoad != null) {
						_gthis.setState({ module : module},onLoad);
						return;
					}
				}
				_gthis.setState({ module : module, error : false, errorMessage : null});
			})["catch"](function(e) {
				if(!_gthis.available) {
					return;
				}
				_gthis.setState({ error : true, errorMessage : e});
			});
		});
	}
	,__class__: react_router_bundle_BundleWrapper
});
var redux_Redux = require("redux");
var redux__$Redux_Action_$Impl_$ = {};
redux__$Redux_Action_$Impl_$.__name__ = ["redux","_Redux","Action_Impl_"];
redux__$Redux_Action_$Impl_$._new = function(a) {
	var this1 = a;
	return this1;
};
redux__$Redux_Action_$Impl_$.map = function(ev) {
	var e = Type.getEnum(ev);
	var this1 = { type : Type.getEnumName(e), value : ev};
	return this1;
};
var redux_Store = function() { };
redux_Store.__name__ = ["redux","Store"];
redux_Store.prototype = {
	getState: null
	,dispatch: null
	,subscribe: null
	,replaceReducer: null
	,__class__: redux_Store
};
var redux_StoreBuilder = function() { };
redux_StoreBuilder.__name__ = ["redux","StoreBuilder"];
redux_StoreBuilder.mapReducer = function(of,service) {
	var type = Type.getEnumName(of);
	return function(state,action) {
		if(state == null) {
			state = service.initState;
		}
		if(action.type == type) {
			return service.reduce(state,action.value);
		} else {
			return state;
		}
	};
};
redux_StoreBuilder.mapMiddleware = function(of,service) {
	var type = Type.getEnumName(of);
	return function(store) {
		service.store = store;
		return function(next) {
			return function(action) {
				if(action.type == type) {
					var skip = function() {
						return next(action);
					};
					return service.middleware(action.value,skip);
				}
				return next(action);
			};
		};
	};
};
redux_StoreBuilder.createStore = function(rootReducer,initState,enhancer) {
	if(initState == null) {
		initState = { };
	}
	return redux_Redux.createStore(rootReducer,initState,enhancer);
};
var redux_react_IConnectedComponent = function() { };
redux_react_IConnectedComponent.__name__ = ["redux","react","IConnectedComponent"];
var redux_react_Provider = function(props) {
	React_Component.call(this,props);
};
redux_react_Provider.__name__ = ["redux","react","Provider"];
redux_react_Provider.__super__ = React_Component;
redux_react_Provider.prototype = $extend(React_Component.prototype,{
	getChildContext: function() {
		return { store : this.props.store};
	}
	,render: function() {
		haxe_Log.trace(this.props.children,{ fileName : "Provider.hx", lineNumber : 37, className : "redux.react.Provider", methodName : "render"});
		return React.Children.only(this.props.children);
	}
	,__class__: redux_react_Provider
});
var view_Accounting = $hx_exports["default"] = function(props,context) {
	React_Component.call(this,props,context);
};
view_Accounting.__name__ = ["view","Accounting"];
view_Accounting.__super__ = React_Component;
view_Accounting.prototype = $extend(React_Component.prototype,{
	render: function() {
		return { "$$typeof" : $$tre, type : "div", props : { className : "tabComponent"}, key : null, ref : null};
	}
	,__class__: view_Accounting
});
var view_Contacts = $hx_exports["default"] = function(props,context) {
	React_Component.call(this,props,context);
};
view_Contacts.__name__ = ["view","Contacts"];
view_Contacts.__super__ = React_Component;
view_Contacts.prototype = $extend(React_Component.prototype,{
	render: function() {
		return { "$$typeof" : $$tre, type : "div", props : { className : "tabComponent", children : "..."}, key : null, ref : null};
	}
	,__class__: view_Contacts
});
var view_DashBoard = $hx_exports["default"] = function(props,context) {
	this.mounted = false;
	var s = App.store.getState().appWare;
	this.state = { themeColor : s.themeColor};
	React_Component.call(this,props,this.state);
	haxe_Log.trace(this.props,{ fileName : "DashBoard.hx", lineNumber : 39, className : "view.DashBoard", methodName : "new"});
	haxe_Log.trace(this.context,{ fileName : "DashBoard.hx", lineNumber : 40, className : "view.DashBoard", methodName : "new"});
	haxe_Log.trace(this.state,{ fileName : "DashBoard.hx", lineNumber : 41, className : "view.DashBoard", methodName : "new"});
	this.__state = this.mapState(context.store.getState(),props);
	this.state = this.state == null ? this.__state : react_ReactUtil.copy(this.state,this.__state);
};
view_DashBoard.__name__ = ["view","DashBoard"];
view_DashBoard.__interfaces__ = [redux_react_IConnectedComponent];
view_DashBoard.mapStateToProps = function(state) {
	haxe_Log.trace(Reflect.fields(state),{ fileName : "DashBoard.hx", lineNumber : 70, className : "view.DashBoard", methodName : "mapStateToProps"});
	return { locale : state.locale, themeColor : state.themeColor};
};
view_DashBoard.mapDispatchToProps = function(dispatch) {
	haxe_Log.trace(dispatch,{ fileName : "DashBoard.hx", lineNumber : 79, className : "view.DashBoard", methodName : "mapDispatchToProps"});
	return { onClick : function() {
		return { };
	}};
};
view_DashBoard.__super__ = React_Component;
view_DashBoard.prototype = $extend(React_Component.prototype,{
	mounted: null
	,componentWillReceiveProps: function(nextProps) {
		haxe_Log.trace(nextProps,{ fileName : "DashBoard.hx", lineNumber : 47, className : "view.DashBoard", methodName : "componentWillReceiveProps"});
		React_Component.prototype.componentWillReceiveProps.call(this,nextProps);
	}
	,componentDidMount: function() {
		this.mounted = true;
		this.__unsubscribe = this.context.store.subscribe($bind(this,this.__connect));
	}
	,mapState: function(state,props) {
		var s = App.store.getState().appWare;
		haxe_Log.trace(s.themeColor,{ fileName : "DashBoard.hx", lineNumber : 59, className : "view.DashBoard", methodName : "mapState"});
		if(this.mounted) {
			this.setState(function(_) {
				return { themeColor : s.themeColor};
			});
		}
		haxe_Log.trace(this.state,{ fileName : "DashBoard.hx", lineNumber : 64, className : "view.DashBoard", methodName : "mapState"});
		return props;
	}
	,setThemeColor: function() {
		haxe_Log.trace("ok",{ fileName : "DashBoard.hx", lineNumber : 87, className : "view.DashBoard", methodName : "setThemeColor"});
		App.store.dispatch(redux__$Redux_Action_$Impl_$.map(action_AppAction.SetTheme("violet")));
	}
	,render: function() {
		haxe_Log.trace(this.state,{ fileName : "DashBoard.hx", lineNumber : 94, className : "view.DashBoard", methodName : "render"});
		var c = this.state.themeColor;
		var tmp = $$tre;
		var tmp1 = { "$$typeof" : $$tre, type : "h3", props : { children : { "$$typeof" : $$tre, type : "div", props : { style : { color : c}, children : ["Route:",this.props.location.pathname]}, key : null, ref : null}}, key : null, ref : null};
		var tmp2 = { "$$typeof" : $$tre, type : "form", props : { id : "user-login", children : [{ "$$typeof" : $$tre, type : "label", props : { htmlFor : "user.firstName", children : "Vorname:"}, key : null, ref : null},React.createElement(react_redux_form_ControlText,{ id : "user.firstName", model : "user.firstName"}),{ "$$typeof" : $$tre, type : "button", props : { type : "submit", className : "mb-4 btn btn-primary", children : "Submit "}, key : null, ref : null},"\t\t\t\t\t"]}, key : null, ref : null};
		var tmp3 = { "$$typeof" : $$tre, type : "span", props : { children : "Download"}, key : null, ref : null};
		var tmp4 = React.createElement(Icon,{ small : true},{ "$$typeof" : $$tre, type : "i", props : { className : "fa fa-download"}, key : null, ref : null});
		return { $$typeof : tmp, type : "div", props : { className : "tabComponent", children : [tmp1,tmp2,React.createElement(bulma_$components_Button,{ success : true, onClick : $bind(this,this.setThemeColor)},tmp3,tmp4)]}, key : null, ref : null};
	}
	,dispatch: function(action) {
		return this.context.store.dispatch(action);
	}
	,__unsubscribe: null
	,__state: null
	,__connect: function() {
		if(this.__unsubscribe != null) {
			var state = this.mapState(this.context.store.getState(),this.props);
			if(this.__state == null || !react_ReactUtil.shallowCompare(this.__state,state)) {
				this.__state = state;
				this.setState(state);
			}
		}
	}
	,componentWillUnmount: function() {
		if(this.__unsubscribe != null) {
			this.__unsubscribe();
			this.__unsubscribe = null;
		}
		this.__state = null;
	}
	,__class__: view_DashBoard
});
var view_NavTabs = function(props,context) {
	haxe_Log.trace(Reflect.fields(props),{ fileName : "NavTabs.hx", lineNumber : 22, className : "view.NavTabs", methodName : "new"});
	React_Component.call(this,props,context);
};
view_NavTabs.__name__ = ["view","NavTabs"];
view_NavTabs.__super__ = React_Component;
view_NavTabs.prototype = $extend(React_Component.prototype,{
	render: function() {
		haxe_Log.trace(Reflect.field(this.props,"computedMatch"),{ fileName : "NavTabs.hx", lineNumber : 29, className : "view.NavTabs", methodName : "render"});
		var tmp = $$tre;
		var tmp1 = { "$$typeof" : $$tre, type : $bind(this,this.TabLink), props : Object.assign({ },this.props,{ to : "/dashboard", children : "DashBoard"}), key : null, ref : null};
		var tmp2 = { "$$typeof" : $$tre, type : $bind(this,this.TabLink), props : Object.assign({ },this.props,{ to : "/qc", children : "QC"}), key : null, ref : null};
		var tmp3 = { "$$typeof" : $$tre, type : $bind(this,this.TabLink), props : Object.assign({ },this.props,{ to : "/contacts", children : "Kontakte"}), key : null, ref : null};
		var tmp4 = { "$$typeof" : $$tre, type : $bind(this,this.TabLink), props : Object.assign({ },this.props,{ to : "/accounting", children : "Buchhaltung"}), key : null, ref : null};
		var tmp5 = $$tre;
		var tmp6 = Object.assign({ },this.props,{ to : "/reports", children : "Berichte"});
		var tmp7 = React.createElement(bulma_$components_Tabs,{ centered : true, boxed : true},"\t\t\t\t","\t\t\t\t",{ $$typeof : tmp, type : "ul", props : { children : [tmp1," ",tmp2,tmp3,tmp4,{ $$typeof : tmp5, type : $bind(this,this.TabLink), props : tmp6, key : null, ref : null}]}, key : null, ref : null});
		return React.createElement(React.Fragment,{ },tmp7,"\t",this.props.children);
	}
	,TabLink: function(rprops) {
		return { "$$typeof" : $$tre, type : "li", props : { className : rprops.to == rprops.location.pathname ? "is-active" : "", children : React.createElement(react_router_NavLink,{ to : rprops.to},rprops.children)}, key : null, ref : null};
	}
	,__class__: view_NavTabs
});
var view_QC = $hx_exports["default"] = function(props,context) {
	React_Component.call(this,props,context);
};
view_QC.__name__ = ["view","QC"];
view_QC.onLoad = function() {
	haxe_Log.trace(666,{ fileName : "QC.hx", lineNumber : 13, className : "view.QC", methodName : "onLoad"});
};
view_QC.__super__ = React_Component;
view_QC.prototype = $extend(React_Component.prototype,{
	render: function() {
		haxe_Log.trace(this.props,{ fileName : "QC.hx", lineNumber : 17, className : "view.QC", methodName : "render"});
		return { "$$typeof" : $$tre, type : "div", props : { className : "tabComponent", children : { "$$typeof" : $$tre, type : "h3", props : { children : { "$$typeof" : $$tre, type : "div", props : { style : { color : "green"}, children : ["Route:",this.props.location.pathname]}, key : null, ref : null}}, key : null, ref : null}}, key : null, ref : null};
	}
	,__class__: view_QC
});
var view_Reports = $hx_exports["default"] = function(props,context) {
	React_Component.call(this,props,context);
};
view_Reports.__name__ = ["view","Reports"];
view_Reports.__super__ = React_Component;
view_Reports.prototype = $extend(React_Component.prototype,{
	render: function() {
		return { "$$typeof" : $$tre, type : "div", props : { className : "tabComponent"}, key : null, ref : null};
	}
	,__class__: view_Reports
});
var view_Statistics = function(props,context) {
	React_Component.call(this,props,context);
};
view_Statistics.__name__ = ["view","Statistics"];
view_Statistics.__super__ = React_Component;
view_Statistics.prototype = $extend(React_Component.prototype,{
	render: function() {
		return { "$$typeof" : $$tre, type : "div", props : { className : "", children : { "$$typeof" : $$tre, type : "h1", props : { children : "Statistics"}, key : null, ref : null}}, key : null, ref : null};
	}
	,__class__: view_Statistics
});
var view_UiView = function(props,state) {
	this.tabList = [{ "key" : 1, "component" : view_DashBoard, "label" : "DashBoard", "url" : "/dashboard"},{ "key" : 2, "component" : view_Contacts, "label" : "Contacts", "url" : "/contacts"},{ "key" : 3, "component" : view_QC, "label" : "QC", "url" : "/qc"},{ "key" : 4, "component" : view_Accounting, "label" : "Buchhaltung", "url" : "/accounting"},{ "key" : 5, "component" : view_Reports, "label" : "Berichte", "url" : "/reports"}];
	haxe_Log.trace(props,{ fileName : "UiView.hx", lineNumber : 59, className : "view.UiView", methodName : "new"});
	haxe_Log.trace(state,{ fileName : "UiView.hx", lineNumber : 60, className : "view.UiView", methodName : "new"});
	React_Component.call(this,props,state);
	haxe_Log.trace(this.props,{ fileName : "UiView.hx", lineNumber : 63, className : "view.UiView", methodName : "new"});
};
view_UiView.__name__ = ["view","UiView"];
view_UiView.__super__ = React_Component;
view_UiView.prototype = $extend(React_Component.prototype,{
	browserHistory: null
	,componentDidCatch: function(error,info) {
		this.setState({ hasError : true});
		haxe_Log.trace(error,{ fileName : "UiView.hx", lineNumber : 71, className : "view.UiView", methodName : "componentDidCatch"});
	}
	,componentDidMount: function() {
	}
	,tabList: null
	,createRoutes: function() {
		var routes = this.tabList.map(function(el) {
			return React.createElement(react_router_Route,{ path : el.url, component : el.component});
		});
		return routes;
	}
	,render: function() {
		var tmp = $$tre;
		var tmp1 = React.createElement(react_router_Route,{ path : "/dashboard", component : react_router_bundle_BundleLoader1.render});
		var tmp2 = React.createElement(react_router_Route,{ path : "/qc", component : react_router_bundle_BundleLoader2.render});
		var tmp3 = React.createElement(react_router_Route,{ path : "/contacts", component : react_router_bundle_BundleLoader3.render});
		var tmp4 = React.createElement(react_router_Route,{ path : "/accounting", component : react_router_bundle_BundleLoader4.render});
		var tmp5 = React.createElement(react_router_Route,{ path : "/reports", component : react_router_bundle_BundleLoader5.render});
		var tmp6 = React.createElement(react_router_Switch,{ },{ $$typeof : tmp, type : view_NavTabs, props : { children : [tmp1,tmp2,tmp3,tmp4,tmp5,"\t\t\t\t\t\t"]}, key : null, ref : null});
		return React.createElement(react_router_BrowserRouter,{ },tmp6);
	}
	,renderContent: function() {
		if(this.state.component == null) {
			return { "$$typeof" : $$tre, type : "span", props : { children : "Loading..."}, key : null, ref : null};
		} else {
			return { "$$typeof" : $$tre, type : this.state.component, props : { }, key : null, ref : null};
		}
	}
	,navLinks: function(tabs) {
		var nav = tabs.map(function(tab) {
			return { "$$typeof" : $$tre, type : "ul", props : { children : { "$$typeof" : $$tre, type : "li", props : { children : { "$$typeof" : $$tre, type : "a", props : { href : tab.url, children : tab.label}, key : tab.id, ref : null}}, key : null, ref : null}}, key : null, ref : null};
		});
		haxe_Log.trace(nav,{ fileName : "UiView.hx", lineNumber : 197, className : "view.UiView", methodName : "navLinks"});
		return nav;
	}
	,navWrapper: function(tabList) {
		var navWrap = { "$$typeof" : $$tre, type : "ul", props : { }, key : null, ref : null};
		navWrap = React.Children.only(navWrap);
		haxe_Log.trace(navWrap,{ fileName : "UiView.hx", lineNumber : 210, className : "view.UiView", methodName : "navWrapper"});
		haxe_Log.trace(navWrap,{ fileName : "UiView.hx", lineNumber : 211, className : "view.UiView", methodName : "navWrapper"});
		haxe_Log.trace("OK",{ fileName : "UiView.hx", lineNumber : 212, className : "view.UiView", methodName : "navWrapper"});
		return navWrap;
	}
	,__class__: view_UiView
});
var view_User = function(props,state,context) {
	React_Component.call(this,null,state);
	haxe_Log.trace(props,{ fileName : "User.hx", lineNumber : 27, className : "view.User", methodName : "new"});
	haxe_Log.trace(state,{ fileName : "User.hx", lineNumber : 28, className : "view.User", methodName : "new"});
};
view_User.__name__ = ["view","User"];
view_User.__super__ = React_Component;
view_User.prototype = $extend(React_Component.prototype,{
	__class__: view_User
});
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
String.prototype.__class__ = String;
String.__name__ = ["String"];
Array.__name__ = ["Array"];
App.STYLES = require("./src/App.css");
App.bulma = require("./node_modules/bulma/css/bulma.min.css");
App.fa = require("./node_modules/font-awesome/css/font-awesome.min.css");
App.displayName = "App";
js_Boot.__toStr = ({ }).toString;
me_cunity_debug_Out.suspended = false;
me_cunity_debug_Out.skipFields = [];
me_cunity_debug_Out.skipFunctions = true;
me_cunity_debug_Out.traceToConsole = false;
me_cunity_debug_Out.traceTarget = me_cunity_debug_DebugOutput.NATIVE;
me_cunity_debug_Out.aStack = haxe_CallStack.callStack;
react_router_bundle_BundleWrapper.defaultProps = { loading : react_router_bundle_BundleWrapper.DefaultLoader, error : react_router_bundle_BundleWrapper.DefaultError};
react_router_bundle_BundleWrapper.displayName = "BundleWrapper";
redux_react_Provider.childContextTypes = { store : PropTypes.object.isRequired};
redux_react_Provider.propTypes = { children : PropTypes.element.isRequired};
redux_react_Provider.displayName = "Provider";
view_Accounting.displayName = "Accounting";
view_Contacts.displayName = "Contacts";
view_DashBoard.user = { firstName : "dummy"};
view_DashBoard.contextTypes = { store : PropTypes.object.isRequired};
view_DashBoard.displayName = "DashBoard";
view_NavTabs.displayName = "NavTabs";
view_QC.displayName = "QC";
view_Reports.displayName = "Reports";
view_Statistics.CONFIG = require("./src/config.json");
view_Statistics.displayName = "Statistics";
view_UiView.displayName = "UiView";
view_User.displayName = "User";
Go.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
